channels:
- uibcdf
- conda-forge
dependencies:
- python
- jupyterlab
- sphinx
- pydata-sphinx-theme
- sphinxcontrib-bibtex
- sphinx-remove-toctrees
- sphinx-copybutton
- sphinx-design
- sphinx-favicon
- sphinx-tabs
- myst-nb
