name: Documentation

on:
  workflow_dispatch:

jobs:
  sphinx_docs_to_gh-pages:
    runs-on: ubuntu-latest
    name: Sphinx docs to gh-pages
    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Additional info about the build
        shell: bash
        run: |
          uname -a

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Setup conda env
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: devtools/conda_env.yaml
          environment-name: docs
          condarc: |
            channels:
              - uibcdf
              - conda-forge
            channel_priority: strict
          create-args: >-
            python=3.12

      - name: Info conda
        shell: bash -l {0}
        run: |
          micromamba activate docs
          micromamba info
          micromamba list

      - name: Running the Sphinx to gh-pages Action
        uses: uibcdf/action-sphinx-docs-to-gh-pages@v2.1.0
        with:
          sphinx-opts: '-j auto'
